apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-10-18T18:07:37Z"
  generation: 1
  labels:
    app: demo
  name: demo
  namespace: default
  resourceVersion: "61689"
  uid: e92ef106-4cfc-46bc-aeb9-5f21619b3e8a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
        - image: aadilsajjad1/my-image1
          imagePullPolicy: Always
          name: my-image1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}